### ISSUE TITLE
POST Requests Timeout

### ISSUE THREAD

**Issue by ArctoranDev** [DenizenScript/Webizen#4]
So I've basically just started using the requests to receive data using Github webhooks, problem is get requests work but post requests as far as the error tells me timesout.

**Comment by mcmonkey4eva** [comment]
POST request support was never fully implemented.
This project's status currently stands, per the readme, as: `Not actively maintained beyond bare minimum, but should function fine.`

While it may or may not be revived or replaced in the future, for the time being there will not be any active feature development.

This might be changed via a PR.... if any community contributors would like to put some work into Webizen.

**Comment by ArctoranDev** [comment]
Then why was the on post request: event added as well if it was not added fully?

**Comment by mcmonkey4eva** [comment]
Sometimes developers start things then don't finish them.
